    
version: '3'
services:
  app:
    image: node:latest
    working_dir: /app
    container_name: projet-seo
    volumes:
      - .:/app
    ports:
      - 3000:3000
      - 3001:3001
    environment:
      - CHOKIDAR_USEPOLLING=1